import { Box, Grid, Slide, TextField, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

export default function FailurePage() {
    const [isLoading, setLoading] = useState(true)

    useEffect(() => {
        setTimeout(() => {
            setLoading(false)
        }, 1)
    }, [])

    return (
        <>
            <Head>
                <title>Thank you for everything</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/heart.svg" />
            </Head>
            <main className="bg-black w-screen h-screen flex justify-center items-center p-5 text-neutral-300">
                <Slide direction="up" timeout={3000} in={!isLoading}>
                    <Box className="bg-neutral-900 p-5 rounded-xl">
                        <Grid container justifyContent="space-around" alignItems="center">
                            <Grid item xs={4}>
                                <Image src="/frog.gif" width={100} height={100} alt="" />
                            </Grid>
                            <Grid item xs={8}>
                                <Typography >
                                    Bom, espero que continuemos amigos pelo menos :3, você é incrível e é isto. Obrigado por tudo. Desculpa por ter me precipitado tanto.
                                </Typography>
                            </Grid>
                        </Grid>
                    </Box>
                </Slide>
            </main>
        </>
    )
}