import Head from 'next/head'
import { Box, Button, CircularProgress, Slide, Typography } from '@mui/material'
import { useState } from 'react'
import phrases from '../static/phrases.json'

export default function Home() {

  const [isLoading, setLoading] = useState(true)
  const [current, setCurrent] = useState(1)

  function goToNext() {
    setLoading(true)
    if (current < phrases.length) {
      setCurrent(current + 1)
      setLoading(false)
    }
  }

  function goToPrevious() {
    setLoading(true)
    if (current > 1) {
      setCurrent(current - 1)
      setLoading(false)
    }
  }

  return (
    <>
      <Head>
        <title>Welcome, Anna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/heart.svg" />
      </Head>
      <main className="w-screen h-screen bg-black text-white flex justify-center items-center p-5">
        <Box>{isLoading ? (<CircularProgress />) :
          <Slide direction='left' in={!isLoading}>
            <Box className="p-5 border-2 border-white rounded-xl mb-3">
              <Typography fontSize={24}>{phrases.find((phrase) => current == Number(phrase.order))?.text}</Typography>
            </Box>
          </Slide>}
          <Box className={`w-full flex justify-${current > 1 ? 'between' : 'end'}`}>
            {current > 1 && <Button className="text-red-500" onClick={goToPrevious}>Anterior</Button>}
            <Button className="text-red-500" onClick={goToNext}>Próximo</Button>
          </Box>
        </Box>
      </main>
    </>
  )
}
