import Head from 'next/head'
import { Box, Button, CircularProgress, Slide, Typography, Zoom } from '@mui/material'
import { useEffect, useState } from 'react'
import myphrases from '../static/phrases.json'
import { useRouter } from 'next/router'

export default function Home() {

  const [isLoading, setLoading] = useState(true)
  const [current, setCurrent] = useState<any>()
  const [mode, setMode] = useState('DEFAULT')

  const router = useRouter()

  useEffect(() => {
    const lastPhrase = window.localStorage.getItem("lastPhrase")
    console.log(lastPhrase)
    if (!lastPhrase) {
      setCurrent(myphrases.find((phrase) => Number(phrase.order) == 1))
    } else {
      setCurrent(JSON.parse(lastPhrase))
    }
    setLoading(false)
  }, [])

  function goToNext() {
    setLoading(true)
    setTimeout(() => {
      const currentPhrase = findPhraseByOrder(current.order + 1)
      setCurrent(currentPhrase)
      window.localStorage.setItem("lastPhrase", JSON.stringify(currentPhrase))
      setLoading(false)
    }, 1)
  }

  function goToPrevious() {
    setLoading(true)
    setTimeout(() => {
      const currentPhrase = findPhraseByOrder(current.order - 1)
      setCurrent(currentPhrase)
      window.localStorage.setItem("lastPhrase", JSON.stringify(currentPhrase))
      setLoading(false)
    }, 1)
  }

  useEffect(() => {
    if (mode == 'SUCCESS') router.push('/success')
    if (mode == 'FAILURE') router.push('/failure')
  }, [mode, router])

  function findPhraseByOrder(order: number) {
    return myphrases.find((phrase) => Number(phrase.order) == order)
  }

  function yes() {
    setMode('SUCCESS')
  }

  function no() {
    setMode('FAILURE')
  }

  return (
    <>
      <Head>
        <title>This is unusual...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/heart.svg" />
      </Head>
      <main className="w-screen h-screen bg-black text-white flex justify-center items-center p-5">
        {mode == 'DEFAULT' && isLoading ? (<></>) :
          <Zoom timeout={500} in={!isLoading}>
            <Box className="p-5">
              <Box className={`mb-3 w-full flex ${current.order > 1 ? 'justify-between' : 'justify-end'}`}>
                {current.order > 1 && <button className="text-red-500" onClick={goToPrevious}>Previous</button>}
                {current.order < myphrases.length && <button className="text-red-500" onClick={goToNext}>Next</button>}
              </Box>
              <Box className="mb-12 p-5 border-2 border-white rounded-xl">
                <Typography fontSize={24}>{current.text}</Typography>
              </Box>
              <Box className="w-full flex justify-between gap-3 mb-5">
                {current.options?.map((option: any) => (<button onClick={option.id == 1 ? yes : no} className={`bg-opacity-75 hover:bg-opacity-100 rounded-xl w-full p-3 ${option.id == 1 ? 'bg-green-500' : 'bg-red-500'}`} key={option.id}>{option.title}</button>))}
              </Box>
              {current.order == myphrases.length && <Typography fontSize={12} className="text-gray-400">Independently which of them you choose, I'm gratefull for all you have done in so little time</Typography>}
            </Box>
          </Zoom>}
      </main >
    </>
  )
}
